global_frame: map
robot_base_frame: thorvald_001/base_link

footprint: [[0.67, 0.64], [0.67, -0.64], [-0.67, -0.64], [-0.67, 0.64]]

map_layer:
  map_topic: /map

global_inflation_layer:
  inflation_radius: 0.7
  cost_scaling_factor: 2.0

local_inflation_layer:
  inflation_radius: 0.7
  cost_scaling_factor: 2.0

obstacle_layer:
  max_obstacle_height: 2.0
  obstacle_range: 2.5
  raytrace_range: 3.0

  unknown_threshold: 6
  mark_threshold: 0
  
  track_unknown_space: true
  
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {sensor_frame: thorvald_001/hokuyo, data_type: LaserScan, topic: thorvald_001/scan, marking: true, clearing: true}

global_obstacle_layer:
  max_obstacle_height: 2.0
  obstacle_range: 2.5
  raytrace_range: 3.0

  unknown_threshold: 6
  mark_threshold: 0

  track_unknown_space: true

  observation_sources: laser_scan_sensor
  laser_scan_sensor: {sensor_frame: thorvald_001/hokuyo, data_type: LaserScan, topic: thorvald_001/scan, marking: false, clearing: false}


